Ignore intentional unused_self pedantic clippy lint
    error: unused `self` argument
       --> src/runtime.rs:200:28
        |
    200 |         pub fn __into_span(&self) -> T {
        |                            ^^^^^
        |
        = help: consider refactoring to an associated function
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_self
        = note: `-D clippy::unused-self` implied by `-D clippy::pedantic`